version: '2'
services: 
  kibana:
    restart: unless-stopped
    hostname: kibana.example.com
    image: kibana
    links:
      - elasticsearch
    ports:
      - 127.0.0.1:5601:5601
    container_name: kibana
 
  logstash:
    restart: unless-stopped
    hostname: logstash.example.com
    build: ./logstash
    ports:
      - 127.0.0.1:32800:5044
    links:
      - elasticsearch
    container_name: logstash
 
  elasticsearch:
    restart: unless-stopped
    hostname: elasticsearch.example.com
    image: elasticsearch
    volumes:
      - ./elk-data:/usr/share/elasticsearch/data
    container_name: elasticsearch
